apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-worker-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc-uploads.yaml
  - postgres-init-configmap.yaml
  - postgres.yaml
  - redis.yaml
  - mcp-web.yaml
  - api.yaml
  - workers.yaml
  - workers-rag.yaml
  - hpa.yaml
